# Generated by Django 2.2.2 on 2019-12-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordered_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.IntegerField()),
                ('color', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('Image', models.ImageField(max_length=400, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark_as_seen', models.BooleanField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.TextField(max_length=400)),
                ('last_name', models.TextField(max_length=400)),
                ('number', models.BigIntegerField()),
                ('alt_number', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=1500)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('payment_option', models.CharField(default=None, max_length=60)),
                ('delivered', models.BooleanField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Placed by user'), (2, 'seen'), (3, 'delivered'), (4, 'approved by User'), (5, 'In Return request')], default=1)),
                ('promocode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Promocodes')),
            ],
        ),
    ]
