# Generated by Django 2.2.2 on 2019-12-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderprocessing', '0003_auto_20191231_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_products',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderprocessing.Checkout'),
            preserve_default=False,
        ),
    ]
