# Generated by Django 2.2.2 on 2020-01-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderprocessing', '0003_notifications_rerurnrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rerurnrequest',
            name='checkout',
        ),
        migrations.AddField(
            model_name='rerurnrequest',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderprocessing.Ordered_products'),
            preserve_default=False,
        ),
    ]
