# Generated by Django 2.2.2 on 2019-12-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orderprocessing', '0004_ordered_products_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_products',
            name='Product',
        ),
        migrations.AddField(
            model_name='ordered_products',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
    ]
