# Generated by Django 2.2.2 on 2019-12-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderprocessing', '0005_auto_20191231_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_products',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordered_products',
            name='sell_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
