# Generated by Django 2.2.2 on 2020-01-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderprocessing', '0005_auto_20200106_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
