# Generated by Django 2.2.2 on 2020-01-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderprocessing', '0006_delete_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Promocodes'),
        ),
    ]
