# Generated by Django 2.2.2 on 2019-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('describtion', models.TextField(max_length=2000)),
                ('min_transaction', models.PositiveIntegerField(default=0)),
                ('max_cashback', models.PositiveIntegerField()),
                ('cashback_type', models.CharField(choices=[('1', 'Percentage'), ('2', 'Price')], default=1, max_length=1)),
                ('cashback', models.PositiveIntegerField()),
                ('applicabe_for_transactions', models.IntegerField(default=1)),
            ],
        ),
    ]
