# Generated by Django 2.2.2 on 2020-01-03 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='offer_pics')),
                ('discount', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100)])),
                ('end_offer', models.BooleanField(default=False)),
                ('notification', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Promocodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='offer_image')),
                ('code', models.CharField(max_length=100)),
                ('describtion', models.TextField(max_length=2000)),
                ('min_transaction', models.PositiveIntegerField(default=0)),
                ('max_cashback', models.PositiveIntegerField()),
                ('cashback_type', models.CharField(choices=[('1', 'Percentage'), ('2', 'Price')], default=1, max_length=1)),
                ('cashback', models.PositiveIntegerField()),
                ('applicabe_for_transactions', models.IntegerField(default=1)),
            ],
        ),
    ]
