# Generated by Django 2.2.2 on 2020-01-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='add_to_main_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='add_to_sub_header',
            field=models.BooleanField(default=False),
        ),
    ]
