# Generated by Django 2.2.2 on 2019-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='image',
            field=models.ImageField(blank=True, upload_to='offer_image'),
        ),
    ]
