# Generated by Django 2.2.2 on 2019-12-28 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_promocodes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='offer_pics')),
                ('discount', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100)])),
                ('end_offer', models.BooleanField(default=False)),
                ('notification', models.CharField(max_length=4000)),
            ],
        ),
    ]
