# Generated by Django 2.2.2 on 2020-01-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20200128_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': '/offer_products_in'},
        ),
    ]
