# Generated by Django 2.2.2 on 2020-03-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20200128_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offers'},
        ),
    ]
