# Generated by Django 2.2.2 on 2020-01-07 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderprocessing', '0006_delete_notifications'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='checkout',
        ),
        migrations.AddField(
            model_name='notifications',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderprocessing.Ordered_products'),
        ),
    ]
