# Generated by Django 3.0.1 on 2019-12-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color_variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100)),
                ('Image_one', models.ImageField(upload_to='Product_Images')),
                ('Image_two', models.ImageField(blank=True, upload_to='Product_Images')),
                ('Image_three', models.ImageField(blank=True, upload_to='Product_Images')),
                ('Image_four', models.ImageField(blank=True, upload_to='Product_Images')),
            ],
        ),
        migrations.CreateModel(
            name='FinalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.MainCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Size_variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=1000)),
                ('Quantity', models.CharField(max_length=1000)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Color_variation')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=300)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Current_Price', models.IntegerField()),
                ('Offer_price', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=5000)),
                ('Size', models.CharField(blank=True, max_length=250)),
                ('color', models.CharField(blank=True, max_length=500)),
                ('Total_stock', models.IntegerField(blank=True, null=True)),
                ('Keywords', models.TextField(blank=True, max_length=2000)),
                ('Return_allowed', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Product_Images')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('total_ratings', models.IntegerField(default=0)),
                ('Final_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.FinalCategory')),
                ('Main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.MainCategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory')),
            ],
        ),
        migrations.AddField(
            model_name='finalcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.MainCategory'),
        ),
        migrations.AddField(
            model_name='finalcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory'),
        ),
        migrations.AddField(
            model_name='color_variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
