# Generated by Django 2.2.2 on 2020-01-27 08:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimages',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/review_images'), upload_to=''),
        ),
    ]
