# Generated by Django 2.2.2 on 2020-01-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200128_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalcategory',
            options={'verbose_name': 'final_cat'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'products/sub_productsinM_of'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '/products/sub_productsin'},
        ),
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
