# Generated by Django 2.2.2 on 2020-01-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200128_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCategorries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=400)),
                ('sub_heading', models.CharField(max_length=400)),
                ('link_one', models.CharField(max_length=400)),
                ('Image_one', models.ImageField(upload_to='HomePage_Categories')),
                ('link_two', models.CharField(max_length=400)),
            ],
        ),
    ]
