# Generated by Django 2.2.2 on 2020-01-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_homepagecategorries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageCategorries',
            new_name='HomePageCategories',
        ),
    ]
