# Generated by Django 2.2.2 on 2020-01-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200129_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecategories',
            name='Image_two',
            field=models.ImageField(default='hello', upload_to='HomePage_Categories'),
            preserve_default=False,
        ),
    ]
