# Generated by Django 2.2.2 on 2020-01-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_homepagecategories_image_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='HomePage_Categories')),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=400)),
                ('sub_heading', models.CharField(max_length=400)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product_Group')),
            ],
        ),
    ]
