# Generated by Django 2.2.2 on 2020-01-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200129_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_group',
            name='Image',
        ),
        migrations.AddField(
            model_name='category_group',
            name='Image',
            field=models.ImageField(default='1', upload_to='HomePage_Categories'),
            preserve_default=False,
        ),
    ]
