# Generated by Django 2.2.2 on 2020-01-29 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200129_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='HomePage_Categories')),
                ('heading', models.CharField(default='Try out', max_length=400)),
                ('sub_heading', models.CharField(blank=True, max_length=400)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='category_products',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category_Group',
        ),
        migrations.DeleteModel(
            name='Category_Products',
        ),
    ]
