# Generated by Django 2.2.2 on 2020-01-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200129_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_group',
            name='Image',
            field=models.ImageField(blank=True, upload_to='HomePage_Categories'),
        ),
    ]
