# Generated by Django 2.2.2 on 2020-01-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200129_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_group',
            name='sub_heading',
        ),
    ]
