# Generated by Django 2.2.2 on 2020-01-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
