# Generated by Django 2.2.2 on 2020-01-30 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_delete_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_group',
            name='product',
        ),
        migrations.AddField(
            model_name='product_group',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
    ]
