# Generated by Django 2.2.2 on 2020-01-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200130_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_products',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Product_Group'),
            preserve_default=False,
        ),
    ]
