# Generated by Django 2.2.2 on 2020-01-30 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_group_products_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_products',
            name='group',
        ),
        migrations.AddField(
            model_name='product_group',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Group_products'),
            preserve_default=False,
        ),
    ]
