# Generated by Django 2.2.2 on 2020-01-30 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20200130_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_group',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Group_products'),
        ),
    ]
