# Generated by Django 2.2.2 on 2020-01-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200130_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_products',
            name='heading',
            field=models.CharField(blank=True, default='Try out', max_length=400),
        ),
    ]
