# Generated by Django 2.2.2 on 2020-03-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200201_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Main Categories'},
        ),
        migrations.AddField(
            model_name='group_products',
            name='catregory_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Category_set'),
            preserve_default=False,
        ),
    ]
