# Generated by Django 2.2.2 on 2020-03-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20200318_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_products',
            name='categort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Category_set'),
            preserve_default=False,
        ),
    ]
