# Generated by Django 2.2.2 on 2020-03-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20200320_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_products',
            name='category',
        ),
    ]
