# Generated by Django 2.2.2 on 2020-03-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_group_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_products',
            name='category',
        ),
    ]
