# Generated by Django 2.2.2 on 2020-03-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_remove_group_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_set',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Group_products'),
        ),
    ]
