# Generated by Django 2.2.2 on 2020-03-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_category_set_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_products',
            name='heading',
            field=models.CharField(blank=True, default='NEW GROUP', max_length=400),
        ),
    ]
