# Generated by Django 2.2.2 on 2020-04-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20200320_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory'},
        ),
        migrations.AddField(
            model_name='color_variation',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size_variation',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category_set',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group', to='products.Group_products'),
        ),
    ]
